version: '3.8'

services:
  postgres:
    build: .
    container_name: postgres-container
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"