spring:
  jackson:
    time-zone: UTC
  devtools:
    restart:
      exclude: static/**,public/**
  datasource:
    url: jdbc:postgresql://localhost:5432/myapp?serverTimezone=UTC
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /api/admin/docs
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    doc-expansion: none
    syntax-highlight:
      theme: nord
  api-docs:
    path: /api/admin/api-docs