spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect